analyzer:
  errors:
    prefer_final_fields: ignore
    strict_top_level_inference: ignore
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
include: package:flutter_lints/flutter.yaml
